let table = prompt("Enter Any Table Number");
document.write("Table Of " + table);
document.write("<br>");
document.write("<br>");
document.write(table + " X " + 1 + " = " + table * 1);
document.write("<br>");
document.write(table + " X " + 1 + " = " + table * 2);
document.write("<br>");
document.write(table + " X " + 1 + " = " + table * 3);
document.write("<br>");
document.write(table + " X " + 1 + " = " + table * 4);
document.write("<br>");
document.write(table + " X " + 1 + " = " + table * 5);
document.write("<br>");
document.write(table + " X " + 1 + " = " + table * 6);
document.write("<br>");
document.write(table + " X " + 1 + " = " + table * 7);
document.write("<br>");
document.write(table + " X " + 1 + " = " + table * 8);
document.write("<br>");
document.write(table + " X " + 1 + " = " + table * 9);
document.write("<br>");
document.write(table + " X " + 1 + " = " + table * 10);
